# Generated by Django 3.0.8 on 2020-08-16 18:22

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def load_initial_data(apps, schema_editor):
    # Учитываем порядок файлов импорта
    call_command('loaddata', 'Verification.json')
    call_command('loaddata', 'Location.json')
    call_command('loaddata', 'Hero.json')
    call_command('loaddata', 'Contact.json')
    call_command('loaddata', 'Thing.json')
    call_command('loaddata', 'Enemy.json')
    call_command('loaddata', 'Anomaly.json')


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('Contact', 'Контакт'),
                                                    ('Enemy', 'Противник'),
                                                    ('Anomaly', 'Аномалия'),
                                                    ('Location', 'Локация')],
                                           max_length=100, verbose_name='Тип проверки')),
                ('table_id', models.IntegerField(verbose_name='id объекта проверки')),
                ('verification_param', models.CharField(choices=[('strength', 'Сила'),
                                                                 ('stamina', 'Выносливость'),
                                                                 ('observation', 'Наблюдательность'),
                                                                 ('concentration', 'Концентрация'),
                                                                 ('intelligence', 'Интеллект'),
                                                                 ('knowledge', 'Знание'),
                                                                 ('constitution', 'Физическое здоровье'),
                                                                 ('resistance', 'Устойчивость к аномалиям')],
                                                        max_length=100, verbose_name='Проверка параметра')),
                ('verification_value', models.IntegerField(verbose_name='Проверка значения')),
            ]
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название локации')),
                ('description', models.TextField(blank=True, verbose_name='Описание локации')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL,
                                            to='game_anomaly.Location',
                                            verbose_name='Из локации')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL,
                                          to='game_anomaly.Location',
                                          verbose_name='В локацию'))
            ]
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL,
                                                     to='game_anomaly.Location',
                                                     verbose_name='Стартовая локация')),
                ('strength', models.IntegerField(verbose_name='Сила')),
                ('stamina', models.IntegerField(verbose_name='Выносливость')),
                ('observation', models.IntegerField(verbose_name='Наблюдательность')),
                ('concentration', models.IntegerField(verbose_name='Концентрация')),
                ('intelligence', models.IntegerField(verbose_name='Интеллект')),
                ('knowledge', models.IntegerField(verbose_name='Знание')),
                ('constitution', models.IntegerField(verbose_name='Физическое здоровье')),
                ('resistance', models.IntegerField(verbose_name='Устойчивость к аномалиям')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('red', 'Красный'),
                                                   ('green', 'Зеленый')],
                                          default='red', max_length=100, verbose_name='Тип')),
                ('name', models.CharField(max_length=30, verbose_name='Название контакта')),
                ('description', models.TextField(blank=True, verbose_name='Описание контакта')),
                ('specification', models.TextField(blank=True, verbose_name='Спецификация контакта')),
                ('reward', models.CharField(max_length=100, verbose_name='Награда')),
                ('penalty', models.CharField(max_length=100, verbose_name='Штраф')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание контакта')),
                ('type', models.CharField(choices=[('Physical defence', 'Средство защиты от физического урона'),
                                                   ('Anomaly defence', 'Средство защиты от аномалий'),
                                                   ('Equipment', 'Снаряжение'),
                                                   ('Weapon', 'Оружие'),
                                                   ('Scientific equipment', 'Научное оборудование'),
                                                   ('Valuable thing', 'Ценный предмет')],
                                          max_length=100, verbose_name='Тип предмета')),
                ('action', models.CharField(max_length=100, verbose_name='Действие'))
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название противника')),
                ('description', models.TextField(blank=True, verbose_name='Описание противника')),
                ('difficulty_before', models.IntegerField(verbose_name='Сложность при раскрытии')),
                ('difficulty_after', models.IntegerField(verbose_name='Сложность после раскрытия')),
                ('penalty', models.CharField(max_length=100, verbose_name='Штраф'))
            ]
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название аномалии')),
                ('description', models.TextField(blank=True, verbose_name='Описание аномалии')),
                ('penalty', models.CharField(max_length=100, verbose_name='Штраф'))
            ]
        ),

        migrations.RunPython(load_initial_data),
    ],
